# Generated by Django 5.0 on 2026-04-03 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(upload_to='blog/')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Article de Blog',
                'verbose_name_plural': 'Articles de Blog',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='evenements/')),
                ('lieu', models.CharField(default='Place Centrale', max_length=200)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
            },
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('categorie', models.CharField(choices=[('mode', 'Mode'), ('beaute', 'Beauté & Santé'), ('restauration', 'Restauration'), ('technologie', 'Technologie'), ('maison', 'Maison'), ('loisirs', 'Loisirs & Culture'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='magasins/')),
                ('localisation', models.CharField(help_text='Ex: Niveau 1, Aile Nord', max_length=200)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('est_en_vedette', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Magasin',
                'verbose_name_plural': 'Magasins',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='promotions/')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='centre_commercial.magasin')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
            },
        ),
    ]
