# Generated by Django 5.0 on 2026-04-24 22:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Name of brand')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start at')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End at')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Product',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(default='category.jpg', upload_to='products/category')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='BB Shopping', max_length=255, verbose_name='name of store')),
                ('about_us', models.TextField(blank=True, default='Information about the store', help_text='Information about the store', verbose_name='About us')),
                ('address', models.CharField(blank=True, default='Store adress', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, default='Store phone', max_length=255, null=True, verbose_name='Contact Phone')),
                ('email', models.EmailField(default='store@mail.com', max_length=255, verbose_name='Email Address')),
                ('logo', models.ImageField(blank=True, default='', upload_to='store/')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Website Adress')),
            ],
        ),
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('city', models.CharField(choices=[('constantine', 'Constantine'), ('alger', 'Alger'), ('oran', 'Oran'), ('annaba', 'Annaba'), ('setif', 'Sétif'), ('autre', 'Autre')], max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='malls/')),
                ('bg_color', models.CharField(default='linear-gradient(135deg,#1a1a2e,#2d1f6e)', help_text='Ex: linear-gradient(135deg,#1a1a2e,#e91e8c)', max_length=200, verbose_name='Gradient CSS (fallback image)')),
                ('description_short', models.CharField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True, default='Description of the mall', help_text='Description of the mall', verbose_name='Description')),
                ('is_open', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('badge', models.CharField(blank=True, max_length=40, verbose_name='Badge (ex: New, Phare)')),
                ('observation', models.TextField(blank=True, default='', help_text='En cas de fermeture ou autre', verbose_name='Observation')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('number_of_shops', models.IntegerField(default=0)),
                ('number_of_parking_spaces', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opening_date', models.DateField(blank=True, null=True, verbose_name='Opening date (if future)')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='malls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Centre Commercial (Mall)',
                'verbose_name_plural': 'Centres Commerciaux (Malls)',
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Image')),
                ('location', models.CharField(default='Place Centrale', max_length=200, verbose_name='Location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_event', models.DateTimeField(verbose_name='Start event')),
                ('end_event', models.DateTimeField(verbose_name='End event')),
                ('mall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='centre_commercial.mall')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='DisplayBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('image', models.ImageField(upload_to='display_boards/')),
                ('start_publication', models.DateTimeField(auto_now_add=True)),
                ('end_publication', models.DateTimeField()),
                ('mall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='display_boards', to='centre_commercial.mall')),
            ],
            options={
                'verbose_name': 'Display Board',
                'verbose_name_plural': 'Display Boards',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('mall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='centre_commercial.mall')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='Image')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Date publication')),
                ('mall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='centre_commercial.mall')),
            ],
            options={
                'verbose_name': 'Blog Article',
                'verbose_name_plural': 'Blog Articles',
            },
        ),
        migrations.CreateModel(
            name='MallImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='malls/images/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('mall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='centre_commercial.mall')),
            ],
        ),
        migrations.CreateModel(
            name='MallVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='malls/videos/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('mall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='centre_commercial.mall')),
            ],
        ),
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('image', models.ImageField(upload_to='fils_actualites/', verbose_name='Image')),
                ('start_publication', models.DateTimeField(auto_now_add=True, verbose_name='Start publication')),
                ('end_publication', models.DateTimeField(verbose_name='End publication')),
                ('mall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fils_actualites', to='centre_commercial.mall')),
            ],
            options={
                'verbose_name': 'News Feed',
                'verbose_name_plural': 'News Feeds',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Updated at')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total price')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash on Delivery'), ('card', 'Card'), ('transfer', 'Bank Transfer')], default='cash', max_length=20, verbose_name='Payment method')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='centre_commercial.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('available', 'Available'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='processing', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='centre_commercial.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre_commercial.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='centre_commercial.orderitem')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre_commercial.productcategory'),
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=128, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='centre_commercial.product', verbose_name='Product images')),
            ],
            options={
                'verbose_name_plural': 'Product images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('shop_owner', 'Shop Owner'), ('mall_manager', 'Mall Manager'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='Customer', max_length=20)),
                ('image', models.ImageField(default='profiles/default.png', upload_to='profiles/')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of shop')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('mode', 'Mode'), ('beaute', 'Beauté & Santé'), ('restauration', 'Restauration'), ('technologie', 'Technologie'), ('maison', 'Maison'), ('loisirs', 'Loisirs & Culture'), ('sport', 'Sport'), ('cinema', 'Cinéma'), ('autre', 'Autre')], max_length=50, verbose_name='Category')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cover', models.ImageField(upload_to='shops/cover/', verbose_name='Cover')),
                ('logo', models.ImageField(upload_to='shops/logo/', verbose_name='Logo')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('location', models.CharField(help_text='Ex: Niveau 1, Aile Nord', max_length=200, verbose_name='Location')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is featured ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_closed', models.BooleanField(default=False, verbose_name='Is closed ?')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('mall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='centre_commercial.mall')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='promotions/', verbose_name='Image')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='centre_commercial.shop')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='centre_commercial.shop'),
        ),
        migrations.CreateModel(
            name='ShopHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='centre_commercial.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ShopSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('whatsapp', models.URLField(blank=True)),
                ('telegram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='centre_commercial.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ShopValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_validated', models.BooleanField(default=False)),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('period', models.IntegerField(blank=True, choices=[(30, '1 Month'), (90, '3 Months'), (180, '6 Months'), (365, '1 Year')], null=True, verbose_name='Period')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation', to='centre_commercial.shop')),
            ],
        ),
        migrations.CreateModel(
            name='StoreSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, default='', upload_to='store_sections/')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='centre_commercial.store')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('BUSINESS', 'Business')], default='FREE', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, to='centre_commercial.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='centre_commercial.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('shop', 'user')},
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='centre_commercial.shop')),
            ],
            options={
                'unique_together': {('shop', 'day')},
            },
        ),
    ]
