# Generated by Django 5.0 on 2026-04-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_commercial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du mall')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('region', models.CharField(choices=[('constantine', 'Constantine'), ('alger', 'Alger'), ('oran', 'Oran'), ('annaba', 'Annaba'), ('setif', 'Sétif'), ('autre', 'Autre')], max_length=50, verbose_name='Région')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('adresse', models.CharField(max_length=300, verbose_name='Adresse complète')),
                ('image', models.ImageField(blank=True, null=True, upload_to='malls/', verbose_name='Image principale')),
                ('couleur_bg', models.CharField(default='linear-gradient(135deg,#1a1a2e,#2d1f6e)', help_text='Ex: linear-gradient(135deg,#1a1a2e,#e91e8c)', max_length=200, verbose_name='Gradient CSS (fallback image)')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_courte', models.CharField(blank=True, max_length=180, verbose_name='Description courte (aperçu)')),
                ('nombre_boutiques', models.PositiveIntegerField(default=0, verbose_name='Nombre de boutiques')),
                ('horaires', models.CharField(default='10h – 22h', max_length=100, verbose_name="Horaires d'ouverture")),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('est_ouvert', models.BooleanField(default=True, verbose_name='Ouvert ?')),
                ('est_en_vedette', models.BooleanField(default=False, verbose_name='Mis en avant ?')),
                ('ouverture_prevue', models.DateField(blank=True, null=True, verbose_name="Date d'ouverture prévue (si futur)")),
                ('badge', models.CharField(blank=True, max_length=40, verbose_name='Badge (ex: Nouveau, Phare)')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Centre Commercial (Mall)',
                'verbose_name_plural': 'Centres Commerciaux (Malls)',
                'ordering': ['-est_en_vedette', 'nom'],
            },
        ),
    ]
