# Generated by Django 5.0 on 2026-04-24 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_commercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='mall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='centre_commercial.mall'),
        ),
    ]
