# Generated by Django 5.0 on 2026-04-06 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_commercial', '0002_mall'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='mall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='centre_commercial.mall'),
        ),
        migrations.AddField(
            model_name='magasin',
            name='mall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magasins', to='centre_commercial.mall'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='mall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='centre_commercial.mall'),
        ),
    ]
