# Generated by Django 5.0 on 2026-04-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_commercial', '0003_alter_shop_mall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_active',
            new_name='is_actif',
        ),
        migrations.AddField(
            model_name='mall',
            name='is_actif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_actif',
            field=models.BooleanField(default=False),
        ),
    ]
