# Generated by Django 5.0 on 2026-04-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_commercial', '0003_evenement_mall_magasin_mall_promotion_mall'),
    ]

    operations = [
        migrations.AddField(
            model_name='mall',
            name='nombre_places_parking',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de places de parking'),
        ),
        migrations.AlterField(
            model_name='magasin',
            name='categorie',
            field=models.CharField(choices=[('mode', 'Mode'), ('beaute', 'Beauté & Santé'), ('restauration', 'Restauration'), ('technologie', 'Technologie'), ('maison', 'Maison'), ('loisirs', 'Loisirs & Culture'), ('cinema', 'Cinéma'), ('autre', 'Autre')], max_length=50),
        ),
    ]
