# Generated by Django 5.0 on 2026-04-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_commercial', '0004_mall_nombre_places_parking_alter_magasin_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mall',
            name='region',
            field=models.CharField(max_length=100, verbose_name='Région'),
        ),
        migrations.AlterField(
            model_name='mall',
            name='ville',
            field=models.CharField(choices=[('constantine', 'Constantine'), ('alger', 'Alger'), ('oran', 'Oran'), ('annaba', 'Annaba'), ('setif', 'Sétif'), ('autre', 'Autre')], max_length=50, verbose_name='Ville'),
        ),
    ]
