# Generated by Django 5.0 on 2026-05-08 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_commercial', '0004_rename_is_active_product_is_actif_mall_is_actif_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='shop',
        ),
        migrations.AddField(
            model_name='promotion',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='centre_commercial.product'),
        ),
    ]
