# Generated by Django 5.0 on 2026-04-10 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_commercial', '0005_alter_mall_region_alter_mall_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='mall',
        ),
        migrations.AddField(
            model_name='articleblog',
            name='mall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='centre_commercial.mall'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='mall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='centre_commercial.mall'),
        ),
    ]
