# Generated by Django 5.0 on 2026-04-14 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_commercial', '0006_remove_promotion_mall_articleblog_mall_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mall',
            name='horaires',
        ),
        migrations.AddField(
            model_name='mall',
            name='heure_fermeture',
            field=models.TimeField(default='22:00', verbose_name='Heure de fermeture'),
        ),
        migrations.AddField(
            model_name='mall',
            name='heure_ouverture',
            field=models.TimeField(default='10:00', verbose_name="Heure d'ouverture"),
        ),
        migrations.CreateModel(
            name='FilActualites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(upload_to='fils_actualites/')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('date_fin_publication', models.DateTimeField()),
                ('mall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fils_actualites', to='centre_commercial.mall')),
            ],
            options={
                'verbose_name': "Fil d'actualités",
                'verbose_name_plural': "Fils d'actualités",
            },
        ),
        migrations.CreateModel(
            name='MallImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='malls/images/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('mall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='centre_commercial.mall')),
            ],
        ),
        migrations.CreateModel(
            name='MallVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='malls/videos/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('mall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='centre_commercial.mall')),
            ],
        ),
    ]
