# Generated by Django 5.0 on 2026-04-15 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_commercial', '0007_remove_mall_horaires_mall_heure_fermeture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mall',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observation'),
        ),
        migrations.CreateModel(
            name='PaneauAffichage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(upload_to='panneaux_affichage/')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('date_fin_publication', models.DateTimeField()),
                ('mall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panneaux_affichage', to='centre_commercial.mall')),
            ],
            options={
                'verbose_name': "Panneau d'affichage",
                'verbose_name_plural': "Panneaux d'affichage",
            },
        ),
    ]
