# Generated by Django 5.0 on 2026-04-15 13:55

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_commercial', '0008_mall_observation_paneauaffichage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Name of brand')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start at')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End at')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name of product')),
                ('slug', models.SlugField(unique=True)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Old price')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Product',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Product category')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Product/categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Product categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='BB Shopping', max_length=255, verbose_name='name of store')),
                ('about_us', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('address', models.CharField(blank=True, default='Store adress', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, default='Store phone', max_length=255, null=True, verbose_name='Contact Phone')),
                ('email', models.EmailField(default='store@mail.com', max_length=255, verbose_name='Email Address')),
                ('logo', models.ImageField(blank=True, default='', upload_to='store/')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Website Adress')),
            ],
        ),
        migrations.RemoveField(
            model_name='filactualites',
            name='mall',
        ),
        migrations.RemoveField(
            model_name='magasin',
            name='mall',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='magasin',
        ),
        migrations.RemoveField(
            model_name='paneauaffichage',
            name='mall',
        ),
        migrations.AlterModelOptions(
            name='articleblog',
            options={'verbose_name': 'Blog Article', 'verbose_name_plural': 'Blog Articles'},
        ),
        migrations.AlterModelOptions(
            name='mall',
            options={'ordering': ['-is_featured', 'name'], 'verbose_name': 'Centre Commercial (Mall)', 'verbose_name_plural': 'Centres Commerciaux (Malls)'},
        ),
        migrations.RenameField(
            model_name='mall',
            old_name='couleur_bg',
            new_name='color_bg',
        ),
        migrations.RenameField(
            model_name='mall',
            old_name='cree_le',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='mall',
            old_name='modifie_le',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='mall',
            old_name='site_web',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='articleblog',
            name='contenu',
        ),
        migrations.RemoveField(
            model_name='articleblog',
            name='titre',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='cree_le',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='sujet',
        ),
        migrations.RemoveField(
            model_name='mall',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='mall',
            name='description_courte',
        ),
        migrations.RemoveField(
            model_name='mall',
            name='est_en_vedette',
        ),
        migrations.RemoveField(
            model_name='mall',
            name='est_ouvert',
        ),
        migrations.RemoveField(
            model_name='mall',
            name='heure_fermeture',
        ),
        migrations.RemoveField(
            model_name='mall',
            name='heure_ouverture',
        ),
        migrations.RemoveField(
            model_name='mall',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='mall',
            name='nombre_boutiques',
        ),
        migrations.RemoveField(
            model_name='mall',
            name='nombre_places_parking',
        ),
        migrations.RemoveField(
            model_name='mall',
            name='ouverture_prevue',
        ),
        migrations.RemoveField(
            model_name='mall',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='mall',
            name='ville',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='cree_le',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='titre',
        ),
        migrations.AddField(
            model_name='articleblog',
            name='content',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articleblog',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default='', max_length=200, verbose_name='Subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mall',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, verbose_name='Full address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mall',
            name='city',
            field=models.CharField(choices=[('constantine', 'Constantine'), ('alger', 'Alger'), ('oran', 'Oran'), ('annaba', 'Annaba'), ('setif', 'Sétif'), ('autre', 'Autre')], default='', max_length=50, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mall',
            name='closing_time',
            field=models.TimeField(default='22:00', verbose_name='Closing time'),
        ),
        migrations.AddField(
            model_name='mall',
            name='description_short',
            field=models.CharField(blank=True, max_length=180, verbose_name='Short description (preview)'),
        ),
        migrations.AddField(
            model_name='mall',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Is featured ?'),
        ),
        migrations.AddField(
            model_name='mall',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='Is open ?'),
        ),
        migrations.AddField(
            model_name='mall',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Name of mall'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mall',
            name='number_of_parking_spaces',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of parking spaces'),
        ),
        migrations.AddField(
            model_name='mall',
            name='number_of_shops',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of shops'),
        ),
        migrations.AddField(
            model_name='mall',
            name='opening_date',
            field=models.DateField(blank=True, null=True, verbose_name='Opening date (if future)'),
        ),
        migrations.AddField(
            model_name='mall',
            name='opening_time',
            field=models.TimeField(default='10:00', verbose_name='Opening time'),
        ),
        migrations.AddField(
            model_name='mall',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='End date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articleblog',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date publication'),
        ),
        migrations.AlterField(
            model_name='articleblog',
            name='image',
            field=models.ImageField(upload_to='blog/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='mall',
            name='badge',
            field=models.CharField(blank=True, max_length=40, verbose_name='Badge (ex: New, Phare)'),
        ),
        migrations.AlterField(
            model_name='mall',
            name='region',
            field=models.CharField(max_length=100, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(upload_to='promotions/', verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='DisplayBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='display_boards/')),
                ('start_publication', models.DateTimeField(auto_now_add=True)),
                ('end_publication', models.DateTimeField()),
                ('mall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='display_boards', to='centre_commercial.mall')),
            ],
            options={
                'verbose_name': 'Display Board',
                'verbose_name_plural': 'Display Boards',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Image')),
                ('location', models.CharField(default='Place Centrale', max_length=200, verbose_name='Location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_event', models.DateTimeField(verbose_name='Start event')),
                ('end_event', models.DateTimeField(verbose_name='End event')),
                ('mall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='centre_commercial.mall')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField(verbose_name='Content')),
                ('image', models.ImageField(upload_to='fils_actualites/', verbose_name='Image')),
                ('start_publication', models.DateTimeField(auto_now_add=True, verbose_name='Start publication')),
                ('end_publication', models.DateTimeField(verbose_name='End publication')),
                ('mall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fils_actualites', to='centre_commercial.mall')),
            ],
            options={
                'verbose_name': 'News Feed',
                'verbose_name_plural': 'News Feeds',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('address', models.CharField(max_length=255)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash on Delivery'), ('card', 'Card'), ('transfer', 'Bank Transfer')], default='cash', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='centre_commercial.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('available', 'Available'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='processing', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='centre_commercial.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre_commercial.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='centre_commercial.orderitem')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='centre_commercial.productcategory'),
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=128, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='centre_commercial.product', verbose_name='Product images')),
            ],
            options={
                'verbose_name_plural': 'Product images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('is_seller', models.BooleanField(default=False)),
                ('is_validated', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('observation', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('transaction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('transaction_ratio', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage (%)', max_digits=5)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of shop')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('mode', 'Mode'), ('beaute', 'Beauté & Santé'), ('restauration', 'Restauration'), ('technologie', 'Technologie'), ('maison', 'Maison'), ('loisirs', 'Loisirs & Culture'), ('cinema', 'Cinéma'), ('autre', 'Autre')], max_length=50, verbose_name='Category')),
                ('description', models.TextField(verbose_name='Description')),
                ('cover', models.ImageField(upload_to='shops/cover/', verbose_name='Cover')),
                ('logo', models.ImageField(upload_to='shops/logo/', verbose_name='Logo')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('location', models.CharField(help_text='Ex: Niveau 1, Aile Nord', max_length=200, verbose_name='Location')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is featured ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_closed', models.BooleanField(default=False, verbose_name='Is closed ?')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observation')),
                ('mall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='centre_commercial.mall')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='centre_commercial.shop'),
        ),
        migrations.CreateModel(
            name='MagasinSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('whatsapp', models.URLField(blank=True)),
                ('telegram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='centre_commercial.shop')),
            ],
        ),
        migrations.AddField(
            model_name='promotion',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='centre_commercial.shop'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ShopHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='centre_commercial.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ShopReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='centre_commercial.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('shop', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ShopValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_validated', models.BooleanField(default=False)),
                ('observation', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('period', models.IntegerField(blank=True, choices=[(30, '1 Month'), (90, '3 Months'), (180, '6 Months'), (365, '1 Year')], null=True, verbose_name='Period')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation', to='centre_commercial.shop')),
            ],
        ),
        migrations.CreateModel(
            name='StoreSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('image', models.ImageField(blank=True, default='', upload_to='store_sections/')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='centre_commercial.store')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('BUSINESS', 'Business')], default='FREE', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, to='centre_commercial.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Evenement',
        ),
        migrations.DeleteModel(
            name='FilActualites',
        ),
        migrations.DeleteModel(
            name='Magasin',
        ),
        migrations.DeleteModel(
            name='PaneauAffichage',
        ),
    ]
