# Generated by Django 5.0 on 2026-04-15 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_commercial', '0009_brand_product_productcategory_store_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MagasinSocial',
            new_name='ShopSocial',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={},
        ),
        migrations.RenameField(
            model_name='mall',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='cree_le',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='modifie_le',
        ),
        migrations.RemoveField(
            model_name='shopholiday',
            name='name',
        ),
        migrations.AlterField(
            model_name='mall',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='mall',
            name='city',
            field=models.CharField(choices=[('constantine', 'Constantine'), ('alger', 'Alger'), ('oran', 'Oran'), ('annaba', 'Annaba'), ('setif', 'Sétif'), ('autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mall',
            name='closing_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='mall',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mall',
            name='description_short',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='mall',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='malls/'),
        ),
        migrations.AlterField(
            model_name='mall',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mall',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mall',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mall',
            name='number_of_parking_spaces',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mall',
            name='number_of_shops',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mall',
            name='opening_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='mall',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre_commercial.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='centre_commercial.shop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(blank=True, default=2, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
