# Generated by Django 5.0 on 2026-04-15 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_commercial', '0010_rename_magasinsocial_shopsocial_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='centre_commercial.shop'),
        ),
    ]
