# Generated by Django 5.0 on 2026-04-15 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre_commercial', '0011_alter_promotion_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mall',
            old_name='color_bg',
            new_name='bg_color',
        ),
        migrations.RenameField(
            model_name='mall',
            old_name='description_short',
            new_name='short_description',
        ),
    ]
