# Generated by Django 5.0 on 2026-04-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre_commercial', '0013_shop_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mall',
            old_name='short_description',
            new_name='description_short',
        ),
    ]
