# Generated by Django 5.0 on 2026-04-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre_commercial', '0018_alter_product_options_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
